version: '3.8'

services:
  webapp:
    container_name: webapp
    ports:
      - '3000:3000'
    build:
      context: webapp
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.next
