# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vbguest.auto_update = true
  config.vm.box_check_update = false

  # Create Management (mgmt) node
  config.vm.define "osmgmt" do |osmgmt_config|
    osmgmt_config.vm.box = "ubuntu/bionic64"
    osmgmt_config.vm.hostname = "osmgmt"
    osmgmt_config.vm.network :private_network, ip: "192.168.56.10"
    osmgmt_config.vm.provider "virtualbox" do |vb|
      vb.name = "osmgmt"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "1024"
    end

    # Shared folders
    if Vagrant::Util::Platform.windows? then
      # Configuration SPECIFIC for Windows 10 hosts
      osmgmt_config.vm.synced_folder "webapp/", "/home/vagrant/app",
      id: "vagrant-app", owner: "vagrant", group: "vagrant",
      mount_options: ["dmode=0755","fmode=0755"]
      osmgmt_config.vm.synced_folder "deploy/", "/home/vagrant/deploy",
      id: "vagrant-deploy", owner: "vagrant", group: "vagrant",
      mount_options: ["dmode=0755","fmode=0755"]
    else
      osmgmt_config.vm.synced_folder "webapp/", "/home/vagrant/app",
      mount_options: ["dmode=775", "fmode=755"]
      osmgmt_config.vm.synced_folder "deploy/", "/home/vagrant/deploy",
      mount_options: ["dmode=775", "fmode=755"]
    end

    # Provisioning
    osmgmt_config.vm.provision :shell, path: "bootstrap-osmgmt.sh"
  end
end
